add_subdirectory(analysis)
add_subdirectory(control_analysis)
add_subdirectory(controllers)
add_subdirectory(estimators)
add_subdirectory(filters)
add_subdirectory(math)
add_subdirectory(neural_network)
add_subdirectory(optimization)
add_subdirectory(regularization)
add_subdirectory(nonlinear_control)
add_subdirectory(robust_control)
add_subdirectory(solvers)
